logging:
  level:
    root: INFO
    com.cinema: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: WARN

server:
  port: 8080

spring:
  application:
    name: cinema-booking

  jackson:
    serialization:
      write-dates-as-timestamps: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: never

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


app:
  bootstrap:
    enabled: true

  messaging:
    stomp-port: 61613
    use-broker-relay: false

  storage:
    root-dir: uploads
    movie-images-dir: movies
    movie-image-max-size: 5242880
    movie-image-allowed-extensions:
      - jpg
      - jpeg
      - png
      - webp
    min-movie-images: 3

  seating:
    lock-duration-minutes: 10
    cleanup-interval-ms: 60000
